name: Build New Release

on:
  repository_dispatch:
    types: [build_new_release]

  workflow_dispatch:
  
env:
  JELLYFIN_WEB_DIR: ../jellyfin-web/dist
  TIZEN_STUDIO_VER: 4.5.1
  TIZEN_STUDIO_URL: https://download.tizen.org/sdk/Installer/tizen-studio_$TIZEN_STUDIO_VER/web-cli_Tizen_Studio_$TIZEN_STUDIO_VER_ubuntu-64.bin
  TIZEN_STUDIO_FILE: web-cli_Tizen_Studio_$TIZEN_STUDIO_VER_ubuntu-64.bin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: env
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '>=14'
    
      - name: Clone jellyfin-tizen
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'jellyfin/jellyfin-tizen'
          platform: 'github'
          
      - name: Clone jellyfin-web
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'jellyfin/jellyfin-web'
          platform: 'github'
          
      - name: Build jellyfin-web
        run: |
          cd jellyfin-web
          npm ci --no-audit
          cd ..
          
      - name: Build jellyfin-tizen
        run: |
          cd jellyfin-tizen
          npm ci --no-audit

      - name: Check resulting folders
        run: |
          ls
